"""
LSTM training script for weather temperature prediction.

Usage
-----
    python src/dl/train.py

Requirements
------------
    weather_data.csv must exist in the project root (generated by src/main.py
    or by running the data collection pipeline).

Output
------
    best_dl_model.pt  — saved model weights in project root
"""
import os
import sys
import logging

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from src.dl.lstm_model import (
    WeatherLSTM,
    FEATURE_COLS,
    SEQ_LEN,
    N_FEATURES,
    MODEL_PATH,
    FEATURE_MIN,
    FEATURE_MAX,
)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Hyper-parameters
# ---------------------------------------------------------------------------
EPOCHS = 30
BATCH_SIZE = 64
LR = 1e-3
TRAIN_SPLIT = 0.8
CSV_PATH = os.path.join(ROOT, "weather_data.csv")


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class WeatherSequenceDataset(Dataset):
    def __init__(self, sequences: np.ndarray, targets: np.ndarray):
        self.X = torch.tensor(sequences, dtype=torch.float32)
        self.y = torch.tensor(targets, dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]


def build_sequences(df: pd.DataFrame):
    """
    Build (X, y) pairs from the dataframe.

    X: (N, SEQ_LEN, N_FEATURES)
    y: (N, 1)  — next-step normalised temperature
    """
    # Build the required columns
    col_map = {
        "Temperature": "temperature",
        "Humidity": "humidity",
        "Precipitation": "precipitation",
        "Wind Speed": "wind_speed",
        "Month": "month",
        "Hour": "hour",
    }
    rename = {k: v for k, v in col_map.items() if k in df.columns}
    df = df.rename(columns=rename)

    # Fill missing derived columns
    if "month" not in df.columns and "Time" in df.columns:
        df["month"] = pd.to_datetime(df["Time"]).dt.month
    if "hour" not in df.columns and "Time" in df.columns:
        df["hour"] = pd.to_datetime(df["Time"]).dt.hour
    if "precipitation" not in df.columns:
        df["precipitation"] = 0.0
    if "wind_speed" not in df.columns:
        df["wind_speed"] = 0.0

    available = [c for c in FEATURE_COLS if c in df.columns]
    missing = [c for c in FEATURE_COLS if c not in df.columns]
    if missing:
        logger.warning("Missing columns, filling with 0: %s", missing)
        for c in missing:
            df[c] = 0.0

    arr = df[FEATURE_COLS].values.astype(np.float32)

    # Normalise
    denom = FEATURE_MAX - FEATURE_MIN
    denom[denom == 0] = 1.0
    arr_norm = (arr - FEATURE_MIN) / denom

    X, y = [], []
    for i in range(len(arr_norm) - SEQ_LEN):
        X.append(arr_norm[i : i + SEQ_LEN])
        y.append(arr_norm[i + SEQ_LEN, 0])   # temperature column

    return np.array(X, dtype=np.float32), np.array(y, dtype=np.float32)


def train_lstm():
    if not os.path.isfile(CSV_PATH):
        logger.error("weather_data.csv not found at %s", CSV_PATH)
        logger.error(
            "Run the data collection pipeline first: python src/main.py"
        )
        return

    logger.info("Loading dataset from %s", CSV_PATH)
    df = pd.read_csv(CSV_PATH)
    logger.info("Rows: %d", len(df))

    if len(df) < SEQ_LEN + 10:
        logger.error(
            "Dataset too small (%d rows). Need at least %d rows.",
            len(df), SEQ_LEN + 10,
        )
        return

    X, y = build_sequences(df)
    logger.info("Sequences: %d", len(X))

    n_train = int(len(X) * TRAIN_SPLIT)
    X_train, X_val = X[:n_train], X[n_train:]
    y_train, y_val = y[:n_train], y[n_train:]

    train_ds = WeatherSequenceDataset(X_train, y_train)
    val_ds = WeatherSequenceDataset(X_val, y_val)
    train_dl = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
    val_dl = DataLoader(val_ds, batch_size=BATCH_SIZE)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info("Training on %s", device)

    model = WeatherLSTM().to(device)
    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=LR)
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer, patience=5, factor=0.5
    )

    best_val_loss = float("inf")

    for epoch in range(1, EPOCHS + 1):
        # --- train ---
        model.train()
        train_loss = 0.0
        for xb, yb in train_dl:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad()
            pred = model(xb).squeeze()
            loss = criterion(pred, yb)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            train_loss += loss.item() * len(xb)
        train_loss /= len(train_ds)

        # --- validate ---
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for xb, yb in val_dl:
                xb, yb = xb.to(device), yb.to(device)
                pred = model(xb).squeeze()
                val_loss += criterion(pred, yb).item() * len(xb)
        val_loss /= len(val_ds)
        scheduler.step(val_loss)

        logger.info(
            "Epoch %2d/%d  train_loss=%.5f  val_loss=%.5f",
            epoch, EPOCHS, train_loss, val_loss,
        )

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), MODEL_PATH)
            logger.info("  ↑ Best model saved (val_loss=%.5f)", best_val_loss)

    logger.info("Training complete. Model saved to %s", MODEL_PATH)
    logger.info("Best validation MSE: %.5f", best_val_loss)


if __name__ == "__main__":
    train_lstm()
